name: Build and release Stage
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' || github.ref != 'refs/heads/main' }}

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    outputs:
      core: ${{ steps.changed-files-yaml.outputs.core_any_changed }}
      prover: ${{ steps.changed-files-yaml.outputs.prover_any_changed }}
      all: ${{ steps.changed-files-yaml.outputs.all_any_changed }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 2

      - name: Get all test, doc and src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v37
        with:
          files_yaml: |
            # TODO: make it more granular, as already implemented in CI workflow
            # We don't want to be rebuilding and redeploying all the Docker images when eg. only document have changed
            prover:
              - prover/**
              - core/lib/**
              - '!core/lib/zksync_core/**'
            core:
              - core/**
            all:
              - '!core/**'
              - '!prover/**'
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      image_tag_suffix: ${{ steps.generate-tag-suffix.outputs.image_tag_suffix }}
      prover_fri_cpu_key_id: ${{ steps.extract-prover-fri-setup-key-ids.outputs.cpu_short_commit_sha }}
      prover_fri_gpu_key_id: ${{ steps.extract-prover-fri-setup-key-ids.outputs.gpu_short_commit_sha }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Generate image tag suffix
        id: generate-tag-suffix
        run: |
          sha=$(git rev-parse --short HEAD)
          ts=$(date +%s%N | cut -b1-13)
          echo "image_tag_suffix=${sha}-${ts}" >> $GITHUB_OUTPUT


  build-push-tee-prover-images:
    name: Build and push images
    needs: [ setup, changed_files ]
    uses: ./.github/workflows/build-tee-prover-template.yml
    with:
      image_tag_suffix: ${{ needs.setup.outputs.image_tag_suffix }}
